# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ielts_bot_db
      - POSTGRES_USER=ielts_bot_user
      - POSTGRES_PASSWORD=Mr_coolman_23

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - audio_files:/app/audio_files
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DATABASE_URL=postgres://ielts_bot_user:Mr_coolman_23@db:5432/ielts_bot_db
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - HF_TOKEN=${HF_TOKEN}
    depends_on:
      - db

  bot:
    build: .
    command: python manage.py runbot
    volumes:
      - .:/app
      - audio_files:/app/audio_files
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DATABASE_URL=postgres://ielts_bot_user:Mr_coolman_23@db:5432/ielts_bot_db
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - HF_TOKEN=${HF_TOKEN}
    depends_on:
      - db

volumes:
  postgres_data:
  audio_files:
