services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - audio_files:/app/audio_files
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  bot:
    build: .
    command: python manage.py runbot
    volumes:
      - .:/app
      - audio_files:/app/audio_files
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  audio_files:
