# Generated by Django 5.1.5 on 2025-01-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_part_test_question_part_test_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.CharField(default="IELTS", max_length=50),
        ),
    ]
