# Generated by Django 5.1.5 on 2025-01-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_question_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="content_hash",
            field=models.CharField(default="default_hash", max_length=32),
        ),
    ]
