# Generated by Django 5.1.5 on 2025-02-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_question_content_hash'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
