# Generated by Django 5.1.5 on 2025-04-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
